### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by Trandel** [rochejul/npmversion#2]
I'm getting this error:
```
  var r = binding.read(fd, buffer, offset, length, position);
                  ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:731:19)
    at tryReadSync (fs.js:486:20)
    at Object.fs.readFileSync (fs.js:534:19)
    at Function.getCurrentPackageJson (/tmp/tower-4537-AYyf/node_modules/npmversion/lib/version.js:255:37)
    at Function.doIt (/tmp/tower-4537-AYyf/node_modules/npmversion/lib/version.js:148:48)
    at Object.<anonymous> (/tmp/tower-4537-AYyf/node_modules/npmversion/lib/cli.js:19:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

As far as I can tell it's a problem with reading the package.json file. I'm using the cli command:
``` node_modules/npmversion/bin/npmversion --increment patch --git-push --read-only```

I've did some debugging and inside `lib/version.js` in `function static getCurrentPackageJson(cwd)` the cwd is the current working directory without the package filename and the `fs.readFileSync` tries to read the directory instead. 

Regards Tomasz Trznadel

**Comment by Trandel** [comment]
Additional info about environment: 
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'bump-patch' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose run-script [ 'prebump-patch', 'bump-patch', 'postbump-patch' ]
5 info lifecycle project@0.1.16~prebump-patch: project@0.1.16
6 silly lifecycle project@0.1.16~prebump-patch: no script for prebump-patch, continuing
7 info lifecycle project@0.1.16~bump-patch: project@0.1.16
8 verbose lifecycle project@0.1.16~bump-patch: unsafe-perm in lifecycle true
9 verbose lifecycle project@0.1.16~bump-patch: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/tmp/tower-4545-DvZn/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/aws/bin:/root/bin:/opt/aws/bin
10 verbose lifecycle project@0.1.16~bump-patch: CWD: /tmp/tower-4545-DvZn
11 silly lifecycle project@0.1.16~bump-patch: Args: [ '-c',
11 silly lifecycle   './node_modules/npmversion/bin/npmversion --increment patch --git-push' ]
12 silly lifecycle project@0.1.16~bump-patch: Returned: code: 1  signal: null
13 info lifecycle project@0.1.16~bump-patch: Failed to exec bump-patch script
14 verbose stack Error: project@0.1.16 bump-patch: `./node_modules/npmversion/bin/npmversion --increment patch --git-push`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid project@0.1.16
16 verbose cwd /tmp/tower-4545-DvZn
17 error Linux 4.4.11-23.53.amzn1.x86_64
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "bump-patch"
19 error node v6.9.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error project@0.1.16 bump-patch: `./node_modules/npmversion/bin/npmversion --increment patch --git-push`
22 error Exit status 1
23 error Failed at the project@0.1.16 bump-patch script './node_modules/npmversion/bin/npmversion --increment patch --git-push'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the project package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ./node_modules/npmversion/bin/npmversion --increment patch --git-push
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs project
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls project
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by rochejul** [comment]
Indeed, this is a bug:

Currently:
````javascript
let packageJsonContent = fs.readFileSync(cwd ? cwd : path.join(process.cwd(), PACKAGE_JSON_FILENAME));
````

Expected:
````javascript
let packageJsonContent = fs.readFileSync(path.join(cwd ? cwd : process.cwd(), PACKAGE_JSON_FILENAME));
````

The only method I haven't test it :'(

I publish a patch as soon as possible

Regards
